apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None
  ports:
  - port: 27017
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo
subsets:
  - addresses:
      - ip: 10.6.197.19
    ports:
      - port: 27017
