version: '3'
services:
  gw:
    build: src/gw
    container_name: gw
    env_file: src/gw/env
    ports:
      - '9050:9050'
  user:
    build: src/user
    container_name: user
    ports:
      - '9051:9051'
  blog:
    build: src/blog
    container_name: blog
    ports:
      - '9052:9052'
