version: '3'
services:
  mongo:
    image: mongo:4.0.3
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data
      - ./src/mongo/mongo-seed.js:/docker-entrypoint-initdb.d/mongo-seed.js
    restart: always
volumes:
  mongo:
