apiVersion: v1
kind: Service
metadata:
  name: apmsrv
spec:
  clusterIP: None
  ports:
  - port: 8200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: apmsrv
subsets:
  - addresses:
      - ip: 10.6.197.19
    ports:
      - port: 8200
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm
data:
  LOG_REQUESTS: "yes"
  ELASTIC_APM_ACTIVE: "true"
  ELASTIC_APM_SERVER_URL: "http://apmsrv:8200"
  ELASTIC_APM_SECRET_TOKEN: "cb735c172081125c0be0724e91f7cb53" # should be a secret
  ELASTIC_APM_ENVIRONMENT: "prod"
  ELASTIC_APM_TRANSACTION_SAMPLE_RATE: 0.5
  ELASTIC_APM_METRICS_INTERVAL: "10m"
  ELASTIC_APM_LOG_LEVEL: "error"
  ELASTIC_APM_LOG_FILE: "stderr"
