apiVersion: v1
kind: Service
metadata:
  name: gw
  labels:
    app: gw
spec:
  type: NodePort
  ports:
  - port: 9050
  selector:
    app: gw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw
data:
  LOG_REQUESTS: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw
  labels:
    app: gw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gw
  template:
    metadata:
      labels:
        app: gw
    spec:
      containers:
      - name: gw
        image: pokus2000/gw:0.3.0
        ports:
        - containerPort: 9050
        envFrom:
        - configMapRef:
            name: gw
        - configMapRef:
            name: apm
        livenessProbe:
          httpGet:
            path: /ping
            port: 9050
          initialDelaySeconds: 2
          periodSeconds: 10
