apiVersion: v1
kind: Service
metadata:
  name: gw
  labels:
    app: gw
spec:
  type: NodePort
  ports:
  - port: 9050
  selector:
    app: gw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw
  labels:
    app: gw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gw
  template:
    metadata:
      labels:
        app: gw
    spec:
      containers:
      - name: gw
        image: pokus2000/gw:0.2.0
        ports:
        - containerPort: 9050
